name: AI CI/CD Pipeline

on:
  push:
    branches: ["main"]
    paths:
      - '**'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Apt
        run: |
          sudo apt-get update

      - name: Install OpenSSL
        run: sudo apt-get install openssl

      - name: Create AI .env file
        run: |
          cat > .env << 'EOF'
          OPENAPI_URL=${{ secrets.OPENAPI_URL }}
          OPENAPI_KEY=${{ secrets.OPENAPI_KEY }}
          OPEN_AI_KEY=${{ secrets.OPEN_AI_KEY }}
          MONGO_DB_URL=${{ secrets.MONGO_DB_URL }}
          SPREADSHEET_ID=${{ secrets.SPREADSHEET_ID }}
          SPREADSHEET_JSON_KEY=${{ secrets.SPREADSHEET_JSON_KEY }}
          HF_TOKEN=${{ secrets.HF_TOKEN }}
          AI_EC2_HOST=${{ secrets.AI_EC2_HOST }}
          AI_TLS_CRT="${{ secrets.AI_TLS_CRT }}"
          AI_TLS_KEY="${{ secrets.AI_TLS_KEY }}"
          APP_ENV=production
          EOF

      - name: Upload AI directory to EC2
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.AI_EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.AI_EC2_SSH_KEY }}
          source: "./"
          target: "/home/ubuntu"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.AI_EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.AI_EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu

            if ! command -v docker &> /dev/null; then
              sudo apt-get update
              sudo apt-get install -y docker.io
              sudo systemctl start docker
              sudo systemctl enable docker
              sudo usermod -aG docker ubuntu
            fi
            
            if ! command -v docker-compose &> /dev/null; then
              sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi
            
            sudo docker-compose down -v || true
            sudo docker-compose up -d --build
