name: AI CI/CD Pipeline

on:
  push:
    branches: ["main"]
    paths:
      - '**'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Apt
        run: |
          sudo apt-get update

      - name: Install OpenSSL
        run: sudo apt-get install openssl

      - name: Create AI .env file
        run: |
          echo "OPENAPI_URL=${{ secrets.OPENAPI_URL }}" > .env
          echo "OPENAPI_KEY=${{ secrets.OPENAPI_KEY }}" >> .env
          echo "OPEN_AI_KEY=${{ secrets.OPEN_AI_KEY }}" >> .env
          echo "MONGO_DB_URL=${{ secrets.MONGO_DB_URL }}" >> .env
          echo "SPREADSHEET_ID=${{ secrets.SPREADSHEET_ID }}" >> .env
          echo "SPREADSHEET_JSON_KEY=${{ secrets.SPREADSHEET_JSON_KEY }}" >> .env
          echo "HF_TOKEN=${{ secrets.HF_TOKEN }}" >> .env
          echo "AI_EC2_HOST=${{ secrets.AI_EC2_HOST }}" >> .env
          echo "AI_TLS_CRT=\"${{ secrets.AI_TLS_CRT }}\"" >> .env  # 줄바꿈 보존 주의
          echo "AI_TLS_KEY=\"${{ secrets.AI_TLS_KEY }}\"" >> .env
          echo "APP_ENV=production" >> .env

      - name: Upload AI directory to EC2
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.AI_EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.AI_EC2_SSH_KEY }}
          source: "./"
          target: "/home/ubuntu"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.AI_EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.AI_EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu
            docker-compose down -v   
            docker-compose up -d --build 
